[package]
name = "minicloze"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
minreq = { version="2.6.0", features=["https"] }
rand = "0.8.5"
